python 06_extract_text_embeddings.py 0   # Process batch 0
python 06_extract_text_embeddings.py 1   # Process batch 1
python 06_extract_text_embeddings.py 2   # Process batch 2
python 06_extract_text_embeddings.py 3   # Process batch 3
python 06_extract_text_embeddings.py 4   # Process batch 4
python 06_extract_text_embeddings.py 5   # Process batch 5
python 06_extract_text_embeddings.py 6   # Process batch 6
python 06_extract_text_embeddings.py 7   # Process batch 7
python 06_extract_text_embeddings.py 8   # Process batch 8
python 06_extract_text_embeddings.py 9   # Process batch 9
python 06_extract_text_embeddings.py 10  # Process batch 10
python 06_extract_text_embeddings.py 11  # Process batch 11
python 06_extract_text_embeddings.py 12  # Process batch 12
python 06_extract_text_embeddings.py 13  # Process batch 13
python 06_extract_text_embeddings.py 14  # Process batch 14
python 06_extract_text_embeddings.py 15  # Process batch 15
python 06_extract_text_embeddings.py 16  # Process batch 16
python 06_extract_text_embeddings.py 17  # Process batch 17
python 06_extract_text_embeddings.py 18  # Process batch 18
python 06_extract_text_embeddings.py 19  # Process batch 19
python 06_extract_text_embeddings.py 20  # Process batch 20
python 06_extract_text_embeddings.py 21  # Process batch 21
python 06_extract_text_embeddings.py 22  # Process batch 22
python 06_extract_text_embeddings.py 23  # Process batch 23
python 06_extract_text_embeddings.py 24  # Process batch 24
python 06_extract_text_embeddings.py 25  # Process batch 25
python 06_extract_text_embeddings.py 26  # Process batch 26
python 06_extract_text_embeddings.py 27  # Process batch 27
python 06_extract_text_embeddings.py 28  # Process batch 28
python 06_extract_text_embeddings.py 29  # Process batch 29
python 06_extract_text_embeddings.py 30  # Process batch 30
python 06_extract_text_embeddings.py 31  # Process batch 31
python 06_extract_text_embeddings.py 32  # Process batch 32
python 06_extract_text_embeddings.py 33  # Process batch 33
python 06_extract_text_embeddings.py 34  # Process batch 34
python 06_extract_text_embeddings.py 35  # Process batch 35
python 06_extract_text_embeddings.py 36  # Process batch 36
python 06_extract_text_embeddings.py 37  # Process batch 37